name: 'PR Conventions Action'
description: 'Checks a PR that it has valid commits and title'
author: 'paschdan'
inputs:
  token: # change this
    required: false
    description: 'Personal access token (PAT) used to interact with the GitHub API.'
    default: '${{ github.token }}'
  help_url:
    required: false
    description: 'Help Url that is shown when validation does not pass'
    default: 'https://www.conventionalcommits.org/en/v1.0.0/'
  config_file:
    required: false
    description: 'file to use for commitlinting'
  verbose:
    required: false
    description: 'should commitlint be verbose during linting, that means, if valid commits should also be reported'
  create_comment:
    required: false
    description: 'should the action comment on the pr'
  check_title:
    required: false
    description: 'shall the title be checked?'
    default: 'true'
  check_commits:
    required: false
    description: 'shall all commits be checked?'
    default: 'true'
runs:
  using: docker
  image: docker://ghcr.io/paschdan/semantic-pullrequest-action:v1
