name: "Check for semantic PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  commitlint-via-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://alpine
        with:
          args: env
      - uses: docker://ghcr.io/paschdan/semantic-pullrequest-action:v1
        with:
          create_comment: 'true'
          token: ${{ secrets.GH_TOKEN }}

