name: "Check for semantic PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  commitlint: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          config_file: 'commitlint.config.js'
